// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hubdjvohoqcrguylmsaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YmRqdm9ob3Fjcmd1eWxtc2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDE1MDAsImV4cCI6MjA2NTA3NzUwMH0.qTlkpQqCyduOVXU8GaU11g5EagDtFJpJDWhlNXOPW3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);